# 공통 설정
spring:
    # 프로파일
    profiles:
        # 제품 운영 모드 (dev|prod)
        active: dev

    # 다국어
    # 템플릿 엔진
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        encoding: utf-8
        cache: false

    devtools:
        livereload:
            enabled: true
#    messages:
#        basename: i18n/messages
#        encoding:  UTF-8
mybatis:
    type-aliases-package: kr.co.unisem.vms.mapper
    mapper-locations:  mybatis/mapper/**/*.xml
    configuration:
        map-underscore-to-camel-case: true
appconf:
    homeuri: /app/articles

server:
    error:
        path: /error
---
# 개발모드 설정
spring:
    jpa:
        show-sql: true
        hibernate:
            # 스키마 유효성 체크
            ddl-auto: validate
        open-in-view: false
    profiles: dev
    datasource: # DB 설정
        url: jdbc:mysql://127.0.0.1:3306/vms?useUnicode=yes&characterEncoding=UTF-8
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: Uniiot12!@
        tomcat:
            max-active: 50
            max-idle: 20
            min-idle: 15

server:
    port: 80 # 서버 웹포트

logging:
    file: logs/web-dev.log
    level:
        root: info
        kr.co.unisem: info
        org:
            mybatis: info
            hibernate:
                SQL: info
                type.descriptor.sql.BasicBinder: info

---
# 제품모드 설정
spring:
    profiles: prod
    datasource: # DB 설정
        url: jdbc:mysql://127.0.0.1:3306/vms?useUnicode=yes&characterEncoding=UTF-8
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: Uniiot12!@
        tomcat:
            max-active: 50
            max-idle: 20
            min-idle: 15

server:
    port: 8080 # 서버 웹포트

logging:
    file: logs/web-prod.log
    level:
        root: info
        kr.co.unisem: info
        org:
            mybatis: info
            hibernate:
                SQL: info
                type.descriptor.sql.BasicBinder: info

